# Generated by Django 6.0.8 on 2026-10-06 11:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_initial_pos_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='kind',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('supplier', 'branch', 'reference'), name='unique_supplier_branch_invoice'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.purchase'),
        ),
    ]
