# Generated by Django 6.0.8 on 2026-10-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_classify_seeded_payment_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zreading',
            name='items_sold',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
